using Microsoft.VisualBasic.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;
using static map_editor_3D.src.Projection;

namespace map_editor_3D.src
{
    internal class MeshObject
    {
        public MeshObject()
        {
            GenerateSphereMesh();
            SphereVertexArray = SphereVertices.ToArray();
            SphereIndexArray = SphereIndices.ToArray();
        }

        public Vector3[] CubeVertices = new Vector3[] {
            new Vector3(-0.5f, -0.5f, -0.5f),
            new Vector3( 0.5f, -0.5f, -0.5f),
            new Vector3( 0.5f,  0.5f, -0.5f),
            new Vector3(-0.5f,  0.5f, -0.5f),
            new Vector3(-0.5f, -0.5f,  0.5f),
            new Vector3( 0.5f, -0.5f,  0.5f),
            new Vector3( 0.5f,  0.5f,  0.5f),
            new Vector3(-0.5f,  0.5f,  0.5f)
        };
        public int[] CubeIndices = new int[] {
            0,1,2, 0,2,3, // back
            4,6,5, 4,7,6, // front
            4,5,1, 4,1,0, // bottom
            7,3,2, 7,2,6, // top
            5,6,2, 5,2,1, // right
            4,0,3, 4,3,7  // left
        };

        public Vector3[] PyramidVertices = new Vector3[] {
            new Vector3(-0.5f, 0, -0.5f), // base
            new Vector3( 0.5f, 0, -0.5f),
            new Vector3( 0.5f, 0,  0.5f),
            new Vector3(-0.5f, 0,  0.5f),
            new Vector3( 0, 1, 0)          // top
        };
        public int[] PyramidIndices = new int[] {
            0,1,4,
            1,2,4,
            2,3,4,
            3,0,4,
            0,3,2, 0,2,1 // base
        };

        public Vector3[] PlaneVertices = new Vector3[] {
            new Vector3(-0.5f, 0, -0.5f),
            new Vector3( 0.5f, 0, -0.5f),
            new Vector3( 0.5f, 0,  0.5f),
            new Vector3(-0.5f, 0,  0.5f)
        };

        public int[] PlaneIndices = new int[] {
            0,1,2,
            0,2,3
        };

        // Code generated by ChatGPT, essentially uses similar math to a unit circle but in 3D. Doing this by hand would have been a nightmare
        public List<Vector3> SphereVertices = new List<Vector3>();
        public List<int> SphereIndices = new List<int>();

        public Vector3[] SphereVertexArray;
        public int[] SphereIndexArray;
        public void GenerateSphereMesh()
        {
            int latSegments = 20; // latitude lines
            int lonSegments = 20; // longitude lines
            float radius = 0.5f;

            for (int lat = 0; lat <= latSegments; lat++)
            {
                float theta = (float)lat / latSegments * MathF.PI;
                float sinTheta = MathF.Sin(theta);
                float cosTheta = MathF.Cos(theta);

                for (int lon = 0; lon <= lonSegments; lon++)
                {
                    float phi = (float)lon / lonSegments * 2 * MathF.PI;
                    float sinPhi = MathF.Sin(phi);
                    float cosPhi = MathF.Cos(phi);

                    float x = radius * sinTheta * cosPhi;
                    float y = radius * cosTheta;
                    float z = radius * sinTheta * sinPhi;

                    SphereVertices.Add(new Vector3(x, y, z));
                }
            }

            // generate triangle indices
            for (int lat = 0; lat < latSegments; lat++)
            {
                for (int lon = 0; lon < lonSegments; lon++)
                {
                    int first = lat * (lonSegments + 1) + lon;
                    int second = first + lonSegments + 1;

                    SphereIndices.Add(first);
                    SphereIndices.Add(second);
                    SphereIndices.Add(first + 1);

                    SphereIndices.Add(second);
                    SphereIndices.Add(second + 1);
                    SphereIndices.Add(first + 1);
                }
            }
        }
    }
}
